nome = str(input('Digite o seu nome completo:')).strip()
print("Analizando seu nome...")
print("Seu nome em maiúsculas é {}.".format(nome.upper()))
print("Seu nome em minúsculas é {}.".format(nome.lower()))
print("Seu nome tem ao todol {} letras.".format(len(nome) - nome.count(' ')))
#print("Seu primeiro nome tem {} letras.".format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} lentras'.format(separa[0], len(separa[0])))
